# octo authentication server
#server.contextPath: /auth
server:
  port: 8090

keystore:
  password: drunkenOctopus
  
spring:
  mvc:
    dispatchOptionsRequest: true
  application:
    name: octo-auth
      
  datasource:                     
    url: jdbc:oracle:thin:@octocat.crwx5goxs3em.us-east-2.rds.amazonaws.com:1521:ORCL
    username: system_user_db
    password: p4ssw0rd
    driverClassName: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}